### ISSUE TITLE
unable to add upload target google drive

### ISSUE THREAD

**Issue by frathe** [teejee2008/baqpaq#4]
The Wizard does not open a web browser window.
![Setup_google_drive_web_browser_wont_open](https://user-images.githubusercontent.com/5739279/115210395-d1fba780-a0fe-11eb-8105-7891127c151a.gif)

**Comment by teejee2008** [comment]
1. Which is the default web browser on your system? 
2. Did you start the app as normal user or as admin (using the Admin launcher in Application menu)?

Keep the default web browser open and try again. It will open a new tab in the same window.

**Comment by frathe** [comment]
1: Google Chrome (Version 90.0.4430.72)
2: Launched as root user

Did try it with browser open and closed.

**Comment by frathe** [comment]
Oh and this machine is running Pop!_OS 20.10

**Comment by teejee2008** [comment]
Rclone is trying to open Chrome as root user, but Chrome does not support running as root (due to security restrictions).

Run Baqpaq as a normal user and create the remote. Then copy the file .rclone.conf in your home folder to the root user's home directory. 

`sudo cp -vf $HOME/.rclone.conf /root/`

Now run Baqpaq as admin and you will able to select the remote in the dropdown. I'll add a fix for this in the next update.

**Comment by frathe** [comment]
Tryed that but when running it again as admin the drop-down is grayed out:
![image](https://user-images.githubusercontent.com/5739279/115230469-b13e4c80-a114-11eb-9fde-314161d0726c.png)

**Comment by teejee2008** [comment]
Update to v20.12.1

**Comment by frathe** [comment]
Works like a charm :+1:
